ICCOLI_EXTRACTION_TARGETS = [
	{
		"schema_name": "public",
		"table_name": "tb_user_login_log",
		"watermark_col": "login_datetime",
		"fallback_watermark_col": None,
	},
	{
		"schema_name": "public",
		"table_name": "tb_user_personal_info",
		"watermark_col": "update_datetime",
		"fallback_watermark_col": "create_datetime",
	},
	{
		"schema_name": "public",
		"table_name": "tb_user_info",
		"watermark_col": "update_datetime",
		"fallback_watermark_col": "create_datetime",
	},
	{
		"schema_name": "public",
		"table_name": "tb_action_info",
		"watermark_col": "create_datetime",
		"fallback_watermark_col": None,
	},
	{
		"schema_name": "public",
		"table_name": "tb_action_mapper",
		"watermark_col": "create_datetime",
		"fallback_watermark_col": None,
	},
	{
		"schema_name": "public",
		"table_name": "tb_activity_user_log",
		"watermark_col": "create_datetime",
		"fallback_watermark_col": None,
	},
	{
		"schema_name": "public",
		"table_name": "tb_action_user_log",
		"watermark_col": "action_datetime",
		"fallback_watermark_col": None,
	},
	{
		"schema_name": "public",
		"table_name": "tb_loop_push_history",
		"watermark_col": "update_datetime",
		"fallback_watermark_col": "create_datetime",
	},
	{
		"schema_name": "public",
		"table_name": "tb_message_send_hist",
		"watermark_col": "create_datetime",
		"fallback_watermark_col": None,
	},
	{
		"schema_name": "public",
		"table_name": "tb_stats_active_user_cnt",
		"watermark_col": "create_datetime",
		"fallback_watermark_col": None,
	},
	{
		"schema_name": "public",
		"table_name": "tb_stats_avg_login_cnt_log",
		"watermark_col": "create_datetime",
		"fallback_watermark_col": None,
	},
	{
		"schema_name": "public",
		"table_name": "tb_user_activity_info",
		"watermark_col": "update_datetime",
		"fallback_watermark_col": "create_datetime",
	},
	{
		"schema_name": "public",
		"table_name": "tb_user_attendance",
		"watermark_col": "create_datetime",
		"fallback_watermark_col": None,
	},
	{
		"schema_name": "public",
		"table_name": "tb_user_device_info",
		"watermark_col": "update_datetime",
		"fallback_watermark_col": "create_datetime",
	},
	{
		"schema_name": "public",
		"table_name": "tb_stats_menu_visit_log",
		"watermark_col": "visit_datetime",
		"fallback_watermark_col": None,
	},
	{
		"schema_name": "public",
		"table_name": "tb_menu_app",
		"watermark_col": "update_datetime",
		"fallback_watermark_col": "create_datetime",
	},
	{
		"schema_name": "public",
		"table_name": "tb_ext_user_mapper",
		"watermark_col": "create_datetime",
		"fallback_watermark_col": None,
	},
	{
		"schema_name": "public",
		"table_name": "tb_ext_user_preinfo",
		"watermark_col": "update_datetime",
		"fallback_watermark_col": "create_datetime",
	},
	{
		"schema_name": "public",
		"table_name": "tb_ext_user_preinfo",
		"watermark_col": "update_datetime",
		"fallback_watermark_col": "create_datetime",
	},
]